<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:atom="http://www.w3.org/2005/Atom">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html xmlns="http://www.w3.org/1999/xhtml">
			<head>
				<title>XML Sitemap - Fyndable</title>
				<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				<meta name="viewport" content="width=device-width, initial-scale=1.0" />
				<style type="text/css">
					body {
						font-size: 14px;
						font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
						margin: 0;
						color: #333;
						background: #f0f2f5;
					}
					a {
						color: #FF4D00;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					h1 {
						font-size: 28px;
						font-weight: 700;
						margin: 0;
					}

					#description {
						background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
						padding: 40px 40px 30px;
						color: #fff;
					}
					#description .logo {
						font-size: 22px;
						font-weight: 700;
						color: #FF4D00;
						margin-bottom: 10px;
						display: inline-block;
					}
					#description h1 {
						color: #fff;
						margin: 0 0 10px 0;
					}
					#description p {
						margin: 5px 0;
						color: rgba(255,255,255,0.85);
						font-size: 1em;
						line-height: 1.6;
					}
					#description a {
						color: #FF4D00;
						border-bottom: 1px dotted rgba(255,77,0,0.5);
					}
					#description a:hover {
						border-bottom-style: solid;
						text-decoration: none;
					}

					#content {
						padding: 30px;
						background: #f0f2f5;
						max-width: 1100px;
						margin: 0 auto;
					}
					.content-card {
						background: #fff;
						border-radius: 12px;
						box-shadow: 0 2px 8px rgba(0,0,0,0.06);
						overflow: hidden;
					}
					.content-card .card-header {
						padding: 20px 25px;
						border-bottom: 1px solid #eee;
						font-size: 15px;
						color: #666;
					}
					.content-card .card-header strong {
						color: #FF4D00;
						font-size: 18px;
					}
					table {
						border: none;
						border-collapse: collapse;
						font-size: .9em;
						width: 100%;
					}
					th {
						background-color: #1a1a2e;
						color: #fff;
						text-align: left;
						padding: 14px 15px;
						font-size: 13px;
						font-weight: 600;
						text-transform: uppercase;
						letter-spacing: 0.5px;
					}
					td {
						padding: 12px 15px;
						border-bottom: 1px solid #eee;
					}
					tbody tr:nth-child(even) {
						background-color: #fafafa;
					}
					tbody tr:hover {
						background-color: #fff5f0;
					}
					table td a {
						display: inline-block;
						color: #FF4D00;
						word-break: break-all;
					}
					.back-link {
						padding: 15px 25px;
						border-top: 1px solid #eee;
						background: #fafafa;
					}
					.back-link a {
						color: #FF4D00;
						font-size: 13px;
					}
					.footer {
						text-align: center;
						padding: 20px;
						color: #999;
						font-size: 12px;
					}
					.footer a {
						color: #FF4D00;
					}
				</style>
			</head>
			<body>

				<div id="description">
					<div class="logo">Fyndable</div>
					<h1>XML Sitemap</h1>
					<p>
						This XML sitemap is generated by <a href="https://fyndable.com/" target="_blank">Fyndable SEO</a>.
						It is used by search engines like Google to crawl and re-crawl posts, pages, products, images, and archives on your site.
					</p>
					<p>
						Learn more about <a href="http://sitemaps.org" target="_blank">XML sitemaps</a>.
					</p>
				</div>

				<div id="content">
					<div class="content-card">
						<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
							<div class="card-header">
								This sitemap index contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.
							</div>
							<table id="sitemap" cellpadding="3">
								<thead>
									<tr>
										<th width="75%">Sitemap</th>
										<th width="25%">Last Modified</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
										<xsl:variable name="sitemapURL">
											<xsl:value-of select="sitemap:loc"/>
										</xsl:variable>
										<tr>
											<td>
												<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
											</td>
											<td>
												<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
						</xsl:if>

						<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
							<div class="card-header">
								This XML sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
							</div>
							<table id="sitemap" cellpadding="3">
								<thead>
									<tr>
										<th width="75%">URL</th>
										<th width="5%">Images</th>
										<th title="Last Modification Time" width="20%">Last Modified</th>
									</tr>
								</thead>
								<tbody>
									<xsl:for-each select="sitemap:urlset/sitemap:url">
										<tr>
											<td>
												<xsl:variable name="itemURL">
													<xsl:value-of select="sitemap:loc"/>
												</xsl:variable>
												<a href="{$itemURL}">
													<xsl:value-of select="sitemap:loc"/>
												</a>
											</td>
											<td>
												<xsl:value-of select="count(image:image)"/>
											</td>
											<td>
												<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))"/>
											</td>
										</tr>
									</xsl:for-each>
								</tbody>
							</table>
							<div class="back-link">
								<a href="/sitemap_index.xml">&#8592; Back to Sitemap Index</a>
							</div>
						</xsl:if>
					</div>
				</div>

				<div class="footer">
					Generated by <a href="https://fyndable.com/" target="_blank">Fyndable SEO</a>
				</div>

			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
