package com.fyndable.mobile.ui.keywords

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.graphics.Color
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExtendedFloatingActionButton
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewmodel.compose.viewModel
import com.fyndable.mobile.data.store.AuthStore
import com.fyndable.mobile.ui.ScreenViewModelFactory
import com.fyndable.mobile.ui.components.EmptyState
import com.fyndable.mobile.ui.components.ErrorState
import com.fyndable.mobile.ui.components.LoadingState
import com.fyndable.mobile.ui.components.StatusBadge
import com.fyndable.mobile.ui.theme.FyndableBlue
import com.fyndable.mobile.ui.theme.DangerRed
import com.fyndable.mobile.ui.theme.FyndableInk
import com.fyndable.mobile.ui.theme.FyndableMagenta
import com.fyndable.mobile.ui.theme.FyndablePurple
import com.fyndable.mobile.ui.theme.Gray200
import com.fyndable.mobile.ui.theme.Gray500
import com.fyndable.mobile.ui.theme.SuccessGreen
import com.fyndable.mobile.ui.theme.WarningAmber

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun KeywordsScreen(
    authStore: AuthStore,
    viewModel: KeywordsViewModel = viewModel(factory = ScreenViewModelFactory(authStore))
) {
    val state by viewModel.state.collectAsStateWithLifecycle()
    val isGenerating by viewModel.isGenerating.collectAsStateWithLifecycle()
    val generatedKeywords by viewModel.generatedKeywords.collectAsStateWithLifecycle()
    val toast by viewModel.toast.collectAsStateWithLifecycle()
    val snackbarHostState = remember { SnackbarHostState() }
    var showAddSheet by rememberSaveable { mutableStateOf(false) }
    var showGenerated by rememberSaveable { mutableStateOf(false) }
    var searchQuery by rememberSaveable { mutableStateOf("") }

    LaunchedEffect(toast) {
        toast?.let {
            snackbarHostState.showSnackbar(it)
            viewModel.clearToast()
        }
    }

    LaunchedEffect(generatedKeywords) {
        if (generatedKeywords.isNotEmpty()) showGenerated = true
    }

    Scaffold(
        containerColor = androidx.compose.ui.graphics.Color.Transparent,
        snackbarHost = { SnackbarHost(snackbarHostState) },
        floatingActionButton = {
            ExtendedFloatingActionButton(
                onClick = { showAddSheet = true },
                icon = { Icon(Icons.Filled.Add, contentDescription = "Toevoegen") },
                text = { Text("Keyword") }
            )
        }
    ) { padding ->
        Column(modifier = Modifier.fillMaxSize().padding(padding)) {
            // Search bar
            OutlinedTextField(
                value = searchQuery,
                onValueChange = { searchQuery = it },
                placeholder = { Text("Zoek keywords…", color = Gray500) },
                leadingIcon = { Icon(Icons.Filled.Search, contentDescription = null, tint = Gray500) },
                singleLine = true,
                shape = RoundedCornerShape(6.dp),
                colors = OutlinedTextFieldDefaults.colors(
                    focusedContainerColor = Color.White,
                    unfocusedContainerColor = Color.White,
                    focusedBorderColor = FyndablePurple,
                    unfocusedBorderColor = Gray200,
                    focusedTextColor = FyndableInk,
                    unfocusedTextColor = FyndableInk
                ),
                modifier = Modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp)
            )

            when (val s = state) {
                is KeywordsViewModel.UiState.Loading -> LoadingState()
                is KeywordsViewModel.UiState.Error -> ErrorState(s.message)
                is KeywordsViewModel.UiState.Success -> {
                    val filtered = if (searchQuery.isBlank()) s.keywords
                    else s.keywords.filter { it.keyword.contains(searchQuery, ignoreCase = true) }

                    if (filtered.isEmpty()) {
                        EmptyState(
                            icon = Icons.Filled.Search,
                            message = "Nog geen keywords. Tik op + om een keyword toe te voegen of te genereren."
                        )
                    } else {
                        LazyColumn(
                            modifier = Modifier.fillMaxSize(),
                            contentPadding = PaddingValues(16.dp),
                            verticalArrangement = Arrangement.spacedBy(8.dp)
                        ) {
                            items(filtered) { kw ->
                                KeywordCard(keyword = kw)
                            }
                        }
                    }
                }
            }
        }
    }

    // Add keyword bottom sheet
    if (showAddSheet) {
        val sheetState = rememberModalBottomSheetState()
        var kw by remember { mutableStateOf("") }
        var vol by remember { mutableStateOf("") }
        var diff by remember { mutableStateOf("") }

        ModalBottomSheet(
            onDismissRequest = { showAddSheet = false },
            sheetState = sheetState
        ) {
            Column(modifier = Modifier.padding(24.dp)) {
                Text("Keyword toevoegen", style = MaterialTheme.typography.titleLarge)
                Spacer(modifier = Modifier.height(16.dp))
                OutlinedTextField(
                    value = kw,
                    onValueChange = { kw = it },
                    label = { Text("Keyword / onderwerp") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth()
                )
                Spacer(modifier = Modifier.height(12.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    OutlinedTextField(
                        value = vol,
                        onValueChange = { vol = it.filter { c -> c.isDigit() } },
                        label = { Text("Search Volume") },
                        singleLine = true,
                        modifier = Modifier.weight(1f)
                    )
                    OutlinedTextField(
                        value = diff,
                        onValueChange = { diff = it.filter { c -> c.isDigit() } },
                        label = { Text("Difficulty") },
                        singleLine = true,
                        modifier = Modifier.weight(1f)
                    )
                }
                Spacer(modifier = Modifier.height(20.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    TextButton(
                        onClick = {
                            viewModel.addKeyword(kw, vol.toIntOrNull(), diff.toIntOrNull())
                            showAddSheet = false
                        }
                    ) { Text("Toevoegen") }
                    TextButton(
                        onClick = {
                            if (kw.isNotBlank()) {
                                viewModel.generateKeywords(kw)
                                showAddSheet = false
                            }
                        }
                    ) { Text("AI Genereren") }
                }
                Spacer(modifier = Modifier.height(24.dp))
            }
        }
    }

    // Generated keywords bottom sheet
    if (showGenerated && generatedKeywords.isNotEmpty()) {
        val sheetState = rememberModalBottomSheetState()
        ModalBottomSheet(
            onDismissRequest = {
                showGenerated = false
                viewModel.clearGenerated()
            },
            sheetState = sheetState
        ) {
            Column(modifier = Modifier.padding(24.dp)) {
                Text("Gegenereerde keywords", style = MaterialTheme.typography.titleLarge)
                Spacer(modifier = Modifier.height(16.dp))
                LazyColumn(
                    verticalArrangement = Arrangement.spacedBy(4.dp),
                    modifier = Modifier.height(400.dp)
                ) {
                    items(generatedKeywords) { kw ->
                        Row(
                            modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Column(modifier = Modifier.weight(1f)) {
                                Text(kw.keyword, style = MaterialTheme.typography.bodyMedium)
                                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                                    kw.searchVolume?.let {
                                        StatusBadge("Vol: $it", FyndableBlue)
                                    }
                                    kw.difficulty?.let {
                                        val color = if (it <= 30) SuccessGreen
                                        else if (it <= 60) WarningAmber else DangerRed
                                        StatusBadge("Diff: $it", color)
                                    }
                                }
                            }
                            TextButton(onClick = { viewModel.saveGeneratedKeyword(kw) }) {
                                Text("Opslaan")
                            }
                        }
                    }
                }
                Spacer(modifier = Modifier.height(24.dp))
            }
        }
    }

    if (isGenerating) {
        LoadingState(message = "Keywords worden gegenereerd…")
    }
}

@Composable
private fun KeywordCard(keyword: com.fyndable.mobile.data.model.Keyword) {
    Card(
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(
            containerColor = Color.White
        ),
        elevation = CardDefaults.cardElevation(defaultElevation = 1.dp),
        modifier = Modifier.fillMaxWidth()
    ) {
        Row(
            modifier = Modifier.fillMaxWidth().padding(16.dp),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = keyword.keyword,
                    style = MaterialTheme.typography.titleMedium,
                    color = FyndableInk
                )
                Spacer(modifier = Modifier.height(4.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    keyword.searchVolume?.let {
                        StatusBadge("Vol: $it", FyndableBlue)
                    }
                    keyword.difficulty?.let {
                        val color = if (it <= 30) SuccessGreen
                        else if (it <= 60) WarningAmber else DangerRed
                        StatusBadge("$it", color)
                    }
                    keyword.clusterName?.let {
                        StatusBadge(it, FyndableMagenta)
                    }
                }
            }
        }
    }
}
